%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(mesos_state_overlay_pb).
-define(mesos_state_overlay_pb, true).

-define(mesos_state_overlay_pb_gpb_version, "4.0.2").

-ifndef('MESOS_STATE_AGENTOVERLAYINFO.STATE_PB_H').
-define('MESOS_STATE_AGENTOVERLAYINFO.STATE_PB_H', true).
-record('mesos_state_agentoverlayinfo.state',
        {status = 'STATUS_INVALID' :: 'STATUS_INVALID' | 'STATUS_OK' | 'STATUS_FAILED' | 'STATUS_CONFIGURING' | integer() | undefined, % = 1, enum AgentOverlayInfo.State.Status
         error                  :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('MESOS_STATE_VXLANINFO_PB_H').
-define('MESOS_STATE_VXLANINFO_PB_H', true).
-record(mesos_state_vxlaninfo,
        {vni                    :: non_neg_integer(), % = 1, 32 bits
         vtep_name              :: iodata(),        % = 2
         vtep_ip                :: iodata(),        % = 3
         vtep_mac               :: iodata(),        % = 4
         vtep_ip6               :: iodata() | undefined % = 5
        }).
-endif.

-ifndef('MESOS_STATE_BACKENDINFO_PB_H').
-define('MESOS_STATE_BACKENDINFO_PB_H', true).
-record(mesos_state_backendinfo,
        {vxlan                  :: #mesos_state_vxlaninfo{} | undefined % = 1
        }).
-endif.

-ifndef('MESOS_STATE_BRIDGEINFO_PB_H').
-define('MESOS_STATE_BRIDGEINFO_PB_H', true).
-record(mesos_state_bridgeinfo,
        {name                   :: iodata(),        % = 1
         ip                     :: iodata() | undefined, % = 2
         ip6                    :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('MESOS_STATE_OVERLAYINFO_PB_H').
-define('MESOS_STATE_OVERLAYINFO_PB_H', true).
-record(mesos_state_overlayinfo,
        {name                   :: iodata(),        % = 1
         subnet                 :: iodata() | undefined, % = 2
         prefix                 :: non_neg_integer() | undefined, % = 3, 32 bits
         subnet6                :: iodata() | undefined, % = 4
         prefix6                :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('MESOS_STATE_AGENTOVERLAYINFO_PB_H').
-define('MESOS_STATE_AGENTOVERLAYINFO_PB_H', true).
-record(mesos_state_agentoverlayinfo,
        {info                   :: #mesos_state_overlayinfo{}, % = 1
         subnet                 :: iodata() | undefined, % = 2
         mesos_bridge           :: #mesos_state_bridgeinfo{} | undefined, % = 3
         docker_bridge          :: #mesos_state_bridgeinfo{} | undefined, % = 4
         backend                :: #mesos_state_backendinfo{}, % = 5
         state                  :: #'mesos_state_agentoverlayinfo.state'{} | undefined, % = 6
         subnet6                :: iodata() | undefined % = 7
        }).
-endif.

-ifndef('MESOS_STATE_AGENTINFO_PB_H').
-define('MESOS_STATE_AGENTINFO_PB_H', true).
-record(mesos_state_agentinfo,
        {ip                     :: iodata(),        % = 1
         overlays = []          :: [#mesos_state_agentoverlayinfo{}] | undefined % = 2
        }).
-endif.

-ifndef('MESOS_STATE_NETWORKCONFIG_PB_H').
-define('MESOS_STATE_NETWORKCONFIG_PB_H', true).
-record(mesos_state_networkconfig,
        {vtep_subnet            :: iodata(),        % = 1
         vtep_mac_oui           :: iodata(),        % = 2
         overlays = []          :: [#mesos_state_overlayinfo{}] | undefined, % = 3
         vtep_subnet6           :: iodata() | undefined % = 4
        }).
-endif.

-ifndef('MESOS_STATE_STATE_PB_H').
-define('MESOS_STATE_STATE_PB_H', true).
-record(mesos_state_state,
        {network                :: #mesos_state_networkconfig{} | undefined, % = 1
         agents = []            :: [#mesos_state_agentinfo{}] | undefined % = 2
        }).
-endif.

-endif.
